# Generated by Django 5.1.6 on 2025-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_login_otp', '0002_alter_otpuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpuser',
            name='current_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
