# Generated by Django 4.2 on 2025-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_login_otp', '0003_otpuser_current_otp_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='otpuser',
            name='current_otp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
